//go:build !ignore_autogenerated

// Copyright (c) 2025, NVIDIA CORPORATION. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttemptStatus) DeepCopyInto(out *AttemptStatus) {
	*out = *in
	if in.FailedNodes != nil {
		in, out := &in.FailedNodes, &out.FailedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttemptStatus.
func (in *AttemptStatus) DeepCopy() *AttemptStatus {
	if in == nil {
		return nil
	}
	out := new(AttemptStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionMatch) DeepCopyInto(out *ConditionMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionMatch.
func (in *ConditionMatch) DeepCopy() *ConditionMatch {
	if in == nil {
		return nil
	}
	out := new(ConditionMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CordonConfig) DeepCopyInto(out *CordonConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CordonConfig.
func (in *CordonConfig) DeepCopy() *CordonConfig {
	if in == nil {
		return nil
	}
	out := new(CordonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CriteriaSpec) DeepCopyInto(out *CriteriaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CriteriaSpec.
func (in *CriteriaSpec) DeepCopy() *CriteriaSpec {
	if in == nil {
		return nil
	}
	out := new(CriteriaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewNodeValidationConfig) DeepCopyInto(out *NewNodeValidationConfig) {
	*out = *in
	if in.Criteria != nil {
		in, out := &in.Criteria, &out.Criteria
		*out = make([]CriteriaSpec, len(*in))
		copy(*out, *in)
	}
	if in.NewNodeTests != nil {
		in, out := &in.NewNodeTests, &out.NewNodeTests
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.BatchPeriod = in.BatchPeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewNodeValidationConfig.
func (in *NewNodeValidationConfig) DeepCopy() *NewNodeValidationConfig {
	if in == nil {
		return nil
	}
	out := new(NewNodeValidationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSpec) DeepCopyInto(out *NodeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSpec.
func (in *NodeSpec) DeepCopy() *NodeSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfig) DeepCopyInto(out *ProviderConfig) {
	*out = *in
	out.Timeout = in.Timeout
	out.SuccessfulCondition = in.SuccessfulCondition
	out.FailedCondition = in.FailedCondition
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfig.
func (in *ProviderConfig) DeepCopy() *ProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingGateConfig) DeepCopyInto(out *SchedulingGateConfig) {
	*out = *in
	out.Cordon = in.Cordon
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]TaintConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingGateConfig.
func (in *SchedulingGateConfig) DeepCopy() *SchedulingGateConfig {
	if in == nil {
		return nil
	}
	out := new(SchedulingGateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkippedStatus) DeepCopyInto(out *SkippedStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tests != nil {
		in, out := &in.Tests, &out.Tests
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkippedStatus.
func (in *SkippedStatus) DeepCopy() *SkippedStatus {
	if in == nil {
		return nil
	}
	out := new(SkippedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaintConfig) DeepCopyInto(out *TaintConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaintConfig.
func (in *TaintConfig) DeepCopy() *TaintConfig {
	if in == nil {
		return nil
	}
	out := new(TaintConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestConfig) DeepCopyInto(out *TestConfig) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestConfig.
func (in *TestConfig) DeepCopy() *TestConfig {
	if in == nil {
		return nil
	}
	out := new(TestConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestGroupStatus) DeepCopyInto(out *TestGroupStatus) {
	*out = *in
	if in.Attempts != nil {
		in, out := &in.Attempts, &out.Attempts
		*out = make([]AttemptStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestGroupStatus.
func (in *TestGroupStatus) DeepCopy() *TestGroupStatus {
	if in == nil {
		return nil
	}
	out := new(TestGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationConfiguration) DeepCopyInto(out *ValidationConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationConfiguration.
func (in *ValidationConfiguration) DeepCopy() *ValidationConfiguration {
	if in == nil {
		return nil
	}
	out := new(ValidationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValidationConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationConfigurationSpec) DeepCopyInto(out *ValidationConfigurationSpec) {
	*out = *in
	if in.NewNodeValidation != nil {
		in, out := &in.NewNodeValidation, &out.NewNodeValidation
		*out = new(NewNodeValidationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SchedulingGate != nil {
		in, out := &in.SchedulingGate, &out.SchedulingGate
		*out = new(SchedulingGateConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessCriteria != nil {
		in, out := &in.ReadinessCriteria, &out.ReadinessCriteria
		*out = make([]CriteriaSpec, len(*in))
		copy(*out, *in)
	}
	if in.DefaultTests != nil {
		in, out := &in.DefaultTests, &out.DefaultTests
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make(map[string]ProviderConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tests != nil {
		in, out := &in.Tests, &out.Tests
		*out = make(map[string]TestConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationConfigurationSpec.
func (in *ValidationConfigurationSpec) DeepCopy() *ValidationConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ValidationConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationRequest) DeepCopyInto(out *ValidationRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationRequest.
func (in *ValidationRequest) DeepCopy() *ValidationRequest {
	if in == nil {
		return nil
	}
	out := new(ValidationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValidationRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationRequestList) DeepCopyInto(out *ValidationRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ValidationRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationRequestList.
func (in *ValidationRequestList) DeepCopy() *ValidationRequestList {
	if in == nil {
		return nil
	}
	out := new(ValidationRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValidationRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationRequestSpec) DeepCopyInto(out *ValidationRequestSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeSpec, len(*in))
		copy(*out, *in)
	}
	if in.Tests != nil {
		in, out := &in.Tests, &out.Tests
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationRequestSpec.
func (in *ValidationRequestSpec) DeepCopy() *ValidationRequestSpec {
	if in == nil {
		return nil
	}
	out := new(ValidationRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationRequestStatus) DeepCopyInto(out *ValidationRequestStatus) {
	*out = *in
	if in.TestGroups != nil {
		in, out := &in.TestGroups, &out.TestGroups
		*out = make([]TestGroupStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Skipped != nil {
		in, out := &in.Skipped, &out.Skipped
		*out = new(SkippedStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationRequestStatus.
func (in *ValidationRequestStatus) DeepCopy() *ValidationRequestStatus {
	if in == nil {
		return nil
	}
	out := new(ValidationRequestStatus)
	in.DeepCopyInto(out)
	return out
}
