// Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1alpha1

import (
	"google.golang.org/protobuf/proto"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	"github.com/nvidia/nvsentinel/commons/pkg/managed"
	protos "github.com/nvidia/nvsentinel/data-models/pkg/protos"
)

// NVSentinelGroupVersion is the GroupVersion used by ExternalRemediationRequest.
// ExtRR lives in the nvsentinel.dgxc.nvidia.com API group, distinct from the
// janitor.dgxc.nvidia.com group used by RebootNode/GPUReset/TerminateNode.
//
// The version is "v1" to match the CRD generated by protoc-gen-crd, which
// hardcodes "v1" in its plugin source (see plugin.go in
// github.com/yandex/protoc-gen-crd) and does not currently expose a way to
// configure the version per CRD. The HealthEventResource CRD generated by the
// same plugin uses the same v1 convention. Despite the v1 version string, the
// ExtRR API is still pre-stable; ADR-040 governs its lifecycle.
//
// See ADR-040 for the design.
var NVSentinelGroupVersion = schema.GroupVersion{Group: managed.ExtRRApiGroup, Version: managed.ExtRRVersion}

// NVSentinelSchemeBuilder is the SchemeBuilder for the nvsentinel.dgxc.nvidia.com
// API group. It is independent of the SchemeBuilder for janitor.dgxc.nvidia.com
// (defined in groupversion_info.go) so the two groups can be registered
// independently — callers register both with the controller-runtime scheme.
var NVSentinelSchemeBuilder = runtime.NewSchemeBuilder(addNVSentinelKnownTypes)

// AddNVSentinelToScheme adds the nvsentinel.dgxc.nvidia.com/v1 types to the
// given scheme. Called from the janitor manager binary's scheme setup.
var AddNVSentinelToScheme = NVSentinelSchemeBuilder.AddToScheme

func addNVSentinelKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(
		NVSentinelGroupVersion,
		&ExternalRemediationRequest{},
		&ExternalRemediationRequestList{},
	)
	metav1.AddToGroupVersion(scheme, NVSentinelGroupVersion)

	return nil
}

// ExternalRemediationRequest is the Kubernetes API wrapper for the
// proto-generated ExternalRemediationRequestSpec/Status types.
//
// Per ADR-040, the CRD schema is generated from proto (via protoc-gen-crd)
// and the Spec/Status field shapes are owned entirely by the .proto file. This
// wrapper exists ONLY to provide the Kubernetes machinery (TypeMeta,
// ObjectMeta, runtime.Object interface) that the proto-generated types do not
// supply on their own — it deliberately defines no fields of its own beyond
// what Kubernetes requires.
//
// The CRD lives at
// distros/kubernetes/nvsentinel/charts/janitor/crds/external_remediation.crd.yaml
// and is generated from data-models/protobufs/external_remediation.proto.
type ExternalRemediationRequest struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec and Status are pointer fields because the underlying proto types
	// embed protoimpl.MessageState (which contains a sync.Mutex). Copying a
	// proto message by value would trip go vet's copylocks analyzer. Pointer
	// fields also match the CRD schema's `nullable: true` for spec and status
	// produced by protoc-gen-crd.
	Spec   *protos.ExternalRemediationRequestSpec   `json:"spec,omitempty"`
	Status *protos.ExternalRemediationRequestStatus `json:"status,omitempty"`
}

// ExternalRemediationRequestList is the list wrapper, required by the
// runtime.Object interface for list operations.
type ExternalRemediationRequestList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ExternalRemediationRequest `json:"items"`
}

// DeepCopyObject implements runtime.Object.
func (e *ExternalRemediationRequest) DeepCopyObject() runtime.Object {
	if e == nil {
		return nil
	}

	out := new(ExternalRemediationRequest)
	e.DeepCopyInto(out)

	return out
}

// DeepCopy returns a deep copy of the receiver.
func (e *ExternalRemediationRequest) DeepCopy() *ExternalRemediationRequest {
	if e == nil {
		return nil
	}

	return e.DeepCopyObject().(*ExternalRemediationRequest)
}

// DeepCopyInto copies the receiver into out.
//
// Spec and Status are proto messages and use proto.Clone for deep-copy, which
// is the canonical way to deep-copy a protobuf message. nil pointer inputs
// produce nil pointer outputs.
func (e *ExternalRemediationRequest) DeepCopyInto(out *ExternalRemediationRequest) {
	out.TypeMeta = e.TypeMeta
	e.ObjectMeta.DeepCopyInto(&out.ObjectMeta)

	// proto.Clone returns proto.Message but the runtime type is always the same
	// concrete type as the input. The unchecked assertion is the standard pattern
	// — a failed assertion would indicate proto runtime corruption and panicking
	// is the right response (controller-runtime recovers and re-queues). The
	// previous guarded form silently produced a broken deep copy if the
	// assertion failed, which would violate runtime.Object's contract.
	if e.Spec != nil {
		out.Spec = proto.Clone(e.Spec).(*protos.ExternalRemediationRequestSpec)
	}

	if e.Status != nil {
		out.Status = proto.Clone(e.Status).(*protos.ExternalRemediationRequestStatus)
	}
}

// DeepCopyObject implements runtime.Object.
func (l *ExternalRemediationRequestList) DeepCopyObject() runtime.Object {
	if l == nil {
		return nil
	}

	out := new(ExternalRemediationRequestList)
	l.DeepCopyInto(out)

	return out
}

// DeepCopy returns a deep copy of the receiver.
func (l *ExternalRemediationRequestList) DeepCopy() *ExternalRemediationRequestList {
	if l == nil {
		return nil
	}

	return l.DeepCopyObject().(*ExternalRemediationRequestList)
}

// DeepCopyInto copies the receiver into out.
func (l *ExternalRemediationRequestList) DeepCopyInto(out *ExternalRemediationRequestList) {
	out.TypeMeta = l.TypeMeta
	l.ListMeta.DeepCopyInto(&out.ListMeta)

	if l.Items != nil {
		out.Items = make([]ExternalRemediationRequest, len(l.Items))
		for i := range l.Items {
			l.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
