// Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: external_remediation.proto

package protos

import (
	_ "github.com/yandex/protoc-gen-crd/library/go/k8s/protoc_gen_crd/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Condition is the wire equivalent of metav1.Condition. The janitor/pkg/condition
// adapter package converts between this proto representation and metav1.Condition
// at the controller boundary so existing controller-runtime helpers
// (meta.SetStatusCondition, meta.IsStatusConditionTrue) continue to work.
type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the condition type (e.g. "NVSentinelOwnershipReleased",
	// "ExternalRemediationComplete").
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// status is one of "True", "False", "Unknown".
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// observedGeneration is the .metadata.generation that the condition was set
	// based upon.
	ObservedGeneration int64 `protobuf:"varint,3,opt,name=observedGeneration,proto3" json:"observedGeneration,omitempty"`
	// lastTransitionTime is the last time the condition transitioned from one
	// status to another.
	LastTransitionTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lastTransitionTime,proto3" json:"lastTransitionTime,omitempty"`
	// reason contains a programmatic identifier indicating the reason for the
	// condition's last transition (e.g. "ReleaseTaintApplied",
	// "AwaitingExternalSystem", "ReleaseTaintFailed").
	Reason string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	// message is a human-readable message indicating details about the
	// transition.
	Message       string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_external_remediation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_external_remediation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_external_remediation_proto_rawDescGZIP(), []int{0}
}

func (x *Condition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Condition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Condition) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *Condition) GetLastTransitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransitionTime
	}
	return nil
}

func (x *Condition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Condition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ExternalRemediationRequestSpec is the desired state of an ExtRR. The
// HealthEvent describes the fault that produced the ExtRR. The wrapper struct
// leaves room for future ExtRR-specific spec fields (priority, expected duration,
// external-system hints) without requiring changes to the HealthEvent proto.
type ExternalRemediationRequestSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthEvent is a full copy of the triaged HealthEvent that produced this
	// ExtRR. Reuses the existing HealthEvent message by reference; adding a field
	// to HealthEvent propagates here automatically.
	HealthEvent   *HealthEvent `protobuf:"bytes,1,opt,name=healthEvent,proto3" json:"healthEvent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalRemediationRequestSpec) Reset() {
	*x = ExternalRemediationRequestSpec{}
	mi := &file_external_remediation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalRemediationRequestSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalRemediationRequestSpec) ProtoMessage() {}

func (x *ExternalRemediationRequestSpec) ProtoReflect() protoreflect.Message {
	mi := &file_external_remediation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalRemediationRequestSpec.ProtoReflect.Descriptor instead.
func (*ExternalRemediationRequestSpec) Descriptor() ([]byte, []int) {
	return file_external_remediation_proto_rawDescGZIP(), []int{1}
}

func (x *ExternalRemediationRequestSpec) GetHealthEvent() *HealthEvent {
	if x != nil {
		return x.HealthEvent
	}
	return nil
}

// ExternalRemediationRequestStatus is the observed state of an ExtRR. Status
// transitions are driven by the ExtRR reconciler (NVSentinelOwnershipReleased)
// and the external system (ExternalRemediationComplete) — see ADR-040 for the
// condition state machine.
type ExternalRemediationRequestStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// conditions represent the latest available observations of the ExtRR's
	// current state. See ADR-040 for the canonical type names and reasons.
	Conditions []*Condition `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// completionTime is set when the reconciler is done with this ExtRR — the
	// apply terminated (success or NodeNotFound), the close path ran after
	// Complete=True, or operator-initiated cleanup completed. Once set, the
	// reconciler short-circuits to a CheckUnlock-only pass on subsequent
	// reconciles. The TTL reconciler counts the cleanup window from this
	// timestamp, matching the sibling janitor CRDs (RebootNode, TerminateNode,
	// GPUReset).
	CompletionTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=completionTime,proto3" json:"completionTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExternalRemediationRequestStatus) Reset() {
	*x = ExternalRemediationRequestStatus{}
	mi := &file_external_remediation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalRemediationRequestStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalRemediationRequestStatus) ProtoMessage() {}

func (x *ExternalRemediationRequestStatus) ProtoReflect() protoreflect.Message {
	mi := &file_external_remediation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalRemediationRequestStatus.ProtoReflect.Descriptor instead.
func (*ExternalRemediationRequestStatus) Descriptor() ([]byte, []int) {
	return file_external_remediation_proto_rawDescGZIP(), []int{2}
}

func (x *ExternalRemediationRequestStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *ExternalRemediationRequestStatus) GetCompletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionTime
	}
	return nil
}

// ExternalRemediationRequest is the exit door from NVSentinel ownership.
// Created by fault-remediation when triage maps a fault to the CUSTOM
// recommended action (per ADR-036) with a customRecommendedAction configured
// to produce an ExtRR.
//
// See ADR-040 (docs/designs/040-external-remediation-request.md) for the full
// design including the asymmetric ExternalRemediationComplete=True vs False
// handling, the cleanup finalizer, the release taint, and the
// nvsentinel.dgxc.nvidia.com/managed label coordination mechanism.
type ExternalRemediationRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Spec          *ExternalRemediationRequestSpec   `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *ExternalRemediationRequestStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalRemediationRequest) Reset() {
	*x = ExternalRemediationRequest{}
	mi := &file_external_remediation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalRemediationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalRemediationRequest) ProtoMessage() {}

func (x *ExternalRemediationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_external_remediation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalRemediationRequest.ProtoReflect.Descriptor instead.
func (*ExternalRemediationRequest) Descriptor() ([]byte, []int) {
	return file_external_remediation_proto_rawDescGZIP(), []int{3}
}

func (x *ExternalRemediationRequest) GetSpec() *ExternalRemediationRequestSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ExternalRemediationRequest) GetStatus() *ExternalRemediationRequestStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_external_remediation_proto protoreflect.FileDescriptor

const file_external_remediation_proto_rawDesc = "" +
	"\n" +
	"\x1aexternal_remediation.proto\x12\n" +
	"datamodels\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12health_event.proto\x1aNgithub.com/yandex/protoc-gen-crd/library/go/k8s/protoc_gen_crd/proto/crd.proto\"\xe5\x01\n" +
	"\tCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12.\n" +
	"\x12observedGeneration\x18\x03 \x01(\x03R\x12observedGeneration\x12J\n" +
	"\x12lastTransitionTime\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x12lastTransitionTime\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"[\n" +
	"\x1eExternalRemediationRequestSpec\x129\n" +
	"\vhealthEvent\x18\x01 \x01(\v2\x17.datamodels.HealthEventR\vhealthEvent\"\x9d\x01\n" +
	" ExternalRemediationRequestStatus\x125\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x15.datamodels.ConditionR\n" +
	"conditions\x12B\n" +
	"\x0ecompletionTime\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionTime\"\xb2\x02\n" +
	"\x1aExternalRemediationRequest\x12>\n" +
	"\x04spec\x18\x01 \x01(\v2*.datamodels.ExternalRemediationRequestSpecR\x04spec\x12D\n" +
	"\x06status\x18\x02 \x01(\v2,.datamodels.ExternalRemediationRequestStatusR\x06status:\x8d\x01\xaa\xa8\xfd\x97\x02\x86\x01\n" +
	"\x1anvsentinel.dgxc.nvidia.com\x12\x1aExternalRemediationRequest\x1a\x1aexternalremediationrequest\"\x1bexternalremediationrequests*\x05extrr2\n" +
	"nvsentinel@\x01B5Z3github.com/nvidia/nvsentinel/data-models/pkg/protosb\x06proto3"

var (
	file_external_remediation_proto_rawDescOnce sync.Once
	file_external_remediation_proto_rawDescData []byte
)

func file_external_remediation_proto_rawDescGZIP() []byte {
	file_external_remediation_proto_rawDescOnce.Do(func() {
		file_external_remediation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_external_remediation_proto_rawDesc), len(file_external_remediation_proto_rawDesc)))
	})
	return file_external_remediation_proto_rawDescData
}

var file_external_remediation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_external_remediation_proto_goTypes = []any{
	(*Condition)(nil),                        // 0: datamodels.Condition
	(*ExternalRemediationRequestSpec)(nil),   // 1: datamodels.ExternalRemediationRequestSpec
	(*ExternalRemediationRequestStatus)(nil), // 2: datamodels.ExternalRemediationRequestStatus
	(*ExternalRemediationRequest)(nil),       // 3: datamodels.ExternalRemediationRequest
	(*timestamppb.Timestamp)(nil),            // 4: google.protobuf.Timestamp
	(*HealthEvent)(nil),                      // 5: datamodels.HealthEvent
}
var file_external_remediation_proto_depIdxs = []int32{
	4, // 0: datamodels.Condition.lastTransitionTime:type_name -> google.protobuf.Timestamp
	5, // 1: datamodels.ExternalRemediationRequestSpec.healthEvent:type_name -> datamodels.HealthEvent
	0, // 2: datamodels.ExternalRemediationRequestStatus.conditions:type_name -> datamodels.Condition
	4, // 3: datamodels.ExternalRemediationRequestStatus.completionTime:type_name -> google.protobuf.Timestamp
	1, // 4: datamodels.ExternalRemediationRequest.spec:type_name -> datamodels.ExternalRemediationRequestSpec
	2, // 5: datamodels.ExternalRemediationRequest.status:type_name -> datamodels.ExternalRemediationRequestStatus
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_external_remediation_proto_init() }
func file_external_remediation_proto_init() {
	if File_external_remediation_proto != nil {
		return
	}
	file_health_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_external_remediation_proto_rawDesc), len(file_external_remediation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_external_remediation_proto_goTypes,
		DependencyIndexes: file_external_remediation_proto_depIdxs,
		MessageInfos:      file_external_remediation_proto_msgTypes,
	}.Build()
	File_external_remediation_proto = out.File
	file_external_remediation_proto_goTypes = nil
	file_external_remediation_proto_depIdxs = nil
}
