// Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: health_event.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommenedAction int32

const (
	RecommenedAction_NONE            RecommenedAction = 0
	RecommenedAction_COMPONENT_RESET RecommenedAction = 2
	RecommenedAction_CONTACT_SUPPORT RecommenedAction = 5
	RecommenedAction_RESTART_VM      RecommenedAction = 15
	RecommenedAction_RESTART_BM      RecommenedAction = 24
	RecommenedAction_REPLACE_VM      RecommenedAction = 25
	RecommenedAction_UNKNOWN         RecommenedAction = 99
)

// Enum value maps for RecommenedAction.
var (
	RecommenedAction_name = map[int32]string{
		0:  "NONE",
		2:  "COMPONENT_RESET",
		5:  "CONTACT_SUPPORT",
		15: "RESTART_VM",
		24: "RESTART_BM",
		25: "REPLACE_VM",
		99: "UNKNOWN",
	}
	RecommenedAction_value = map[string]int32{
		"NONE":            0,
		"COMPONENT_RESET": 2,
		"CONTACT_SUPPORT": 5,
		"RESTART_VM":      15,
		"RESTART_BM":      24,
		"REPLACE_VM":      25,
		"UNKNOWN":         99,
	}
)

func (x RecommenedAction) Enum() *RecommenedAction {
	p := new(RecommenedAction)
	*p = x
	return p
}

func (x RecommenedAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecommenedAction) Descriptor() protoreflect.EnumDescriptor {
	return file_health_event_proto_enumTypes[0].Descriptor()
}

func (RecommenedAction) Type() protoreflect.EnumType {
	return &file_health_event_proto_enumTypes[0]
}

func (x RecommenedAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecommenedAction.Descriptor instead.
func (RecommenedAction) EnumDescriptor() ([]byte, []int) {
	return file_health_event_proto_rawDescGZIP(), []int{0}
}

type HealthEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Events        []*HealthEvent         `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthEvents) Reset() {
	*x = HealthEvents{}
	mi := &file_health_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthEvents) ProtoMessage() {}

func (x *HealthEvents) ProtoReflect() protoreflect.Message {
	mi := &file_health_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthEvents.ProtoReflect.Descriptor instead.
func (*HealthEvents) Descriptor() ([]byte, []int) {
	return file_health_event_proto_rawDescGZIP(), []int{0}
}

func (x *HealthEvents) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HealthEvents) GetEvents() []*HealthEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entityType,proto3" json:"entityType,omitempty"`
	EntityValue   string                 `protobuf:"bytes,2,opt,name=entityValue,proto3" json:"entityValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_health_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_health_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_health_event_proto_rawDescGZIP(), []int{1}
}

func (x *Entity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Entity) GetEntityValue() string {
	if x != nil {
		return x.EntityValue
	}
	return ""
}

type HealthEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Agent               string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	ComponentClass      string                 `protobuf:"bytes,3,opt,name=componentClass,proto3" json:"componentClass,omitempty"`
	CheckName           string                 `protobuf:"bytes,4,opt,name=checkName,proto3" json:"checkName,omitempty"`
	IsFatal             bool                   `protobuf:"varint,5,opt,name=isFatal,proto3" json:"isFatal,omitempty"`
	IsHealthy           bool                   `protobuf:"varint,6,opt,name=isHealthy,proto3" json:"isHealthy,omitempty"`
	Message             string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	RecommendedAction   RecommenedAction       `protobuf:"varint,8,opt,name=recommendedAction,proto3,enum=datamodels.RecommenedAction" json:"recommendedAction,omitempty"`
	ErrorCode           []string               `protobuf:"bytes,9,rep,name=errorCode,proto3" json:"errorCode,omitempty"`
	EntitiesImpacted    []*Entity              `protobuf:"bytes,10,rep,name=entitiesImpacted,proto3" json:"entitiesImpacted,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GeneratedTimestamp  *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=generatedTimestamp,proto3" json:"generatedTimestamp,omitempty"`
	NodeName            string                 `protobuf:"bytes,13,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	QuarantineOverrides *BehaviourOverrides    `protobuf:"bytes,14,opt,name=quarantineOverrides,proto3" json:"quarantineOverrides,omitempty"`
	DrainOverrides      *BehaviourOverrides    `protobuf:"bytes,15,opt,name=drainOverrides,proto3" json:"drainOverrides,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthEvent) Reset() {
	*x = HealthEvent{}
	mi := &file_health_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthEvent) ProtoMessage() {}

func (x *HealthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_health_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthEvent.ProtoReflect.Descriptor instead.
func (*HealthEvent) Descriptor() ([]byte, []int) {
	return file_health_event_proto_rawDescGZIP(), []int{2}
}

func (x *HealthEvent) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HealthEvent) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *HealthEvent) GetComponentClass() string {
	if x != nil {
		return x.ComponentClass
	}
	return ""
}

func (x *HealthEvent) GetCheckName() string {
	if x != nil {
		return x.CheckName
	}
	return ""
}

func (x *HealthEvent) GetIsFatal() bool {
	if x != nil {
		return x.IsFatal
	}
	return false
}

func (x *HealthEvent) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *HealthEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthEvent) GetRecommendedAction() RecommenedAction {
	if x != nil {
		return x.RecommendedAction
	}
	return RecommenedAction_NONE
}

func (x *HealthEvent) GetErrorCode() []string {
	if x != nil {
		return x.ErrorCode
	}
	return nil
}

func (x *HealthEvent) GetEntitiesImpacted() []*Entity {
	if x != nil {
		return x.EntitiesImpacted
	}
	return nil
}

func (x *HealthEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HealthEvent) GetGeneratedTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedTimestamp
	}
	return nil
}

func (x *HealthEvent) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HealthEvent) GetQuarantineOverrides() *BehaviourOverrides {
	if x != nil {
		return x.QuarantineOverrides
	}
	return nil
}

func (x *HealthEvent) GetDrainOverrides() *BehaviourOverrides {
	if x != nil {
		return x.DrainOverrides
	}
	return nil
}

type BehaviourOverrides struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	Skip          bool                   `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BehaviourOverrides) Reset() {
	*x = BehaviourOverrides{}
	mi := &file_health_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BehaviourOverrides) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BehaviourOverrides) ProtoMessage() {}

func (x *BehaviourOverrides) ProtoReflect() protoreflect.Message {
	mi := &file_health_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BehaviourOverrides.ProtoReflect.Descriptor instead.
func (*BehaviourOverrides) Descriptor() ([]byte, []int) {
	return file_health_event_proto_rawDescGZIP(), []int{3}
}

func (x *BehaviourOverrides) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *BehaviourOverrides) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

var File_health_event_proto protoreflect.FileDescriptor

const file_health_event_proto_rawDesc = "" +
	"\n" +
	"\x12health_event.proto\x12\n" +
	"datamodels\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\fHealthEvents\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12/\n" +
	"\x06events\x18\x02 \x03(\v2\x17.datamodels.HealthEventR\x06events\"J\n" +
	"\x06Entity\x12\x1e\n" +
	"\n" +
	"entityType\x18\x01 \x01(\tR\n" +
	"entityType\x12 \n" +
	"\ventityValue\x18\x02 \x01(\tR\ventityValue\"\x81\x06\n" +
	"\vHealthEvent\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12&\n" +
	"\x0ecomponentClass\x18\x03 \x01(\tR\x0ecomponentClass\x12\x1c\n" +
	"\tcheckName\x18\x04 \x01(\tR\tcheckName\x12\x18\n" +
	"\aisFatal\x18\x05 \x01(\bR\aisFatal\x12\x1c\n" +
	"\tisHealthy\x18\x06 \x01(\bR\tisHealthy\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12J\n" +
	"\x11recommendedAction\x18\b \x01(\x0e2\x1c.datamodels.RecommenedActionR\x11recommendedAction\x12\x1c\n" +
	"\terrorCode\x18\t \x03(\tR\terrorCode\x12>\n" +
	"\x10entitiesImpacted\x18\n" +
	" \x03(\v2\x12.datamodels.EntityR\x10entitiesImpacted\x12A\n" +
	"\bmetadata\x18\v \x03(\v2%.datamodels.HealthEvent.MetadataEntryR\bmetadata\x12J\n" +
	"\x12generatedTimestamp\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x12generatedTimestamp\x12\x1a\n" +
	"\bnodeName\x18\r \x01(\tR\bnodeName\x12P\n" +
	"\x13quarantineOverrides\x18\x0e \x01(\v2\x1e.datamodels.BehaviourOverridesR\x13quarantineOverrides\x12F\n" +
	"\x0edrainOverrides\x18\x0f \x01(\v2\x1e.datamodels.BehaviourOverridesR\x0edrainOverrides\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x12BehaviourOverrides\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\bR\x04skip*\x83\x01\n" +
	"\x10RecommenedAction\x12\b\n" +
	"\x04NONE\x10\x00\x12\x13\n" +
	"\x0fCOMPONENT_RESET\x10\x02\x12\x13\n" +
	"\x0fCONTACT_SUPPORT\x10\x05\x12\x0e\n" +
	"\n" +
	"RESTART_VM\x10\x0f\x12\x0e\n" +
	"\n" +
	"RESTART_BM\x10\x18\x12\x0e\n" +
	"\n" +
	"REPLACE_VM\x10\x19\x12\v\n" +
	"\aUNKNOWN\x10c2_\n" +
	"\x11PlatformConnector\x12J\n" +
	"\x14HealthEventOccuredV1\x12\x18.datamodels.HealthEvents\x1a\x16.google.protobuf.Empty\"\x00B5Z3github.com/nvidia/nvsentinel/data-models/pkg/protosb\x06proto3"

var (
	file_health_event_proto_rawDescOnce sync.Once
	file_health_event_proto_rawDescData []byte
)

func file_health_event_proto_rawDescGZIP() []byte {
	file_health_event_proto_rawDescOnce.Do(func() {
		file_health_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_event_proto_rawDesc), len(file_health_event_proto_rawDesc)))
	})
	return file_health_event_proto_rawDescData
}

var file_health_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_health_event_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_health_event_proto_goTypes = []any{
	(RecommenedAction)(0),         // 0: datamodels.RecommenedAction
	(*HealthEvents)(nil),          // 1: datamodels.HealthEvents
	(*Entity)(nil),                // 2: datamodels.Entity
	(*HealthEvent)(nil),           // 3: datamodels.HealthEvent
	(*BehaviourOverrides)(nil),    // 4: datamodels.BehaviourOverrides
	nil,                           // 5: datamodels.HealthEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_health_event_proto_depIdxs = []int32{
	3, // 0: datamodels.HealthEvents.events:type_name -> datamodels.HealthEvent
	0, // 1: datamodels.HealthEvent.recommendedAction:type_name -> datamodels.RecommenedAction
	2, // 2: datamodels.HealthEvent.entitiesImpacted:type_name -> datamodels.Entity
	5, // 3: datamodels.HealthEvent.metadata:type_name -> datamodels.HealthEvent.MetadataEntry
	6, // 4: datamodels.HealthEvent.generatedTimestamp:type_name -> google.protobuf.Timestamp
	4, // 5: datamodels.HealthEvent.quarantineOverrides:type_name -> datamodels.BehaviourOverrides
	4, // 6: datamodels.HealthEvent.drainOverrides:type_name -> datamodels.BehaviourOverrides
	1, // 7: datamodels.PlatformConnector.HealthEventOccuredV1:input_type -> datamodels.HealthEvents
	7, // 8: datamodels.PlatformConnector.HealthEventOccuredV1:output_type -> google.protobuf.Empty
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_health_event_proto_init() }
func file_health_event_proto_init() {
	if File_health_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_event_proto_rawDesc), len(file_health_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_event_proto_goTypes,
		DependencyIndexes: file_health_event_proto_depIdxs,
		EnumInfos:         file_health_event_proto_enumTypes,
		MessageInfos:      file_health_event_proto_msgTypes,
	}.Build()
	File_health_event_proto = out.File
	file_health_event_proto_goTypes = nil
	file_health_event_proto_depIdxs = nil
}
