// Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: maintenance_request.proto

package protos

import (
	_ "github.com/yandex/protoc-gen-crd/library/go/k8s/protoc_gen_crd/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MaintenanceRequestSpec is the desired state of a MaintenanceRequest. The
// requester supplies a healthEvent describing the preparation NVSentinel must
// perform, and a startTime recording when the maintenance window opens.
type MaintenanceRequestSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthEvent describes the preparation NVSentinel must perform. The
	// reconciler re-emits this event into the pipeline as authored (the
	// requester's recommendedAction stands), so the normal quarantine, drain,
	// and remediation flow fires for whichever action the event names.
	HealthEvent *HealthEvent `protobuf:"bytes,1,opt,name=healthEvent,proto3" json:"healthEvent,omitempty"`
	// startTime is when the maintenance window opens. It is recorded for
	// observability and future scheduling; the node is prepared on creation
	// today.
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceRequestSpec) Reset() {
	*x = MaintenanceRequestSpec{}
	mi := &file_maintenance_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceRequestSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceRequestSpec) ProtoMessage() {}

func (x *MaintenanceRequestSpec) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceRequestSpec.ProtoReflect.Descriptor instead.
func (*MaintenanceRequestSpec) Descriptor() ([]byte, []int) {
	return file_maintenance_request_proto_rawDescGZIP(), []int{0}
}

func (x *MaintenanceRequestSpec) GetHealthEvent() *HealthEvent {
	if x != nil {
		return x.HealthEvent
	}
	return nil
}

func (x *MaintenanceRequestSpec) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// MaintenanceRequestStatus is the observed state of a MaintenanceRequest.
type MaintenanceRequestStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// conditions represent the latest available observations of the MR's
	// current state.
	Conditions    []*Condition `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceRequestStatus) Reset() {
	*x = MaintenanceRequestStatus{}
	mi := &file_maintenance_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceRequestStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceRequestStatus) ProtoMessage() {}

func (x *MaintenanceRequestStatus) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceRequestStatus.ProtoReflect.Descriptor instead.
func (*MaintenanceRequestStatus) Descriptor() ([]byte, []int) {
	return file_maintenance_request_proto_rawDescGZIP(), []int{1}
}

func (x *MaintenanceRequestStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// MaintenanceRequest is the entry door for externally initiated node
// maintenance. An external system or operator creates an MR to tell
// NVSentinel that maintenance is incoming for a node, so NVSentinel
// prepares the node (cordon, drain) before the work begins.
//
// See ADR-051 (docs/designs/051-maintenance-request.md) for the full design.
type MaintenanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// spec is the desired state supplied by the requester.
	Spec *MaintenanceRequestSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	// status is the observed state populated by the controller.
	Status        *MaintenanceRequestStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceRequest) Reset() {
	*x = MaintenanceRequest{}
	mi := &file_maintenance_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceRequest) ProtoMessage() {}

func (x *MaintenanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_maintenance_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceRequest.ProtoReflect.Descriptor instead.
func (*MaintenanceRequest) Descriptor() ([]byte, []int) {
	return file_maintenance_request_proto_rawDescGZIP(), []int{2}
}

func (x *MaintenanceRequest) GetSpec() *MaintenanceRequestSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *MaintenanceRequest) GetStatus() *MaintenanceRequestStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_maintenance_request_proto protoreflect.FileDescriptor

const file_maintenance_request_proto_rawDesc = "" +
	"\n" +
	"\x19maintenance_request.proto\x12\n" +
	"datamodels\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12health_event.proto\x1a\x1aexternal_remediation.proto\x1aNgithub.com/yandex/protoc-gen-crd/library/go/k8s/protoc_gen_crd/proto/crd.proto\"\x8d\x01\n" +
	"\x16MaintenanceRequestSpec\x129\n" +
	"\vhealthEvent\x18\x01 \x01(\v2\x17.datamodels.HealthEventR\vhealthEvent\x128\n" +
	"\tstartTime\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"Q\n" +
	"\x18MaintenanceRequestStatus\x125\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x15.datamodels.ConditionR\n" +
	"conditions\"\xc7\x02\n" +
	"\x12MaintenanceRequest\x126\n" +
	"\x04spec\x18\x01 \x01(\v2\".datamodels.MaintenanceRequestSpecR\x04spec\x12<\n" +
	"\x06status\x18\x02 \x01(\v2$.datamodels.MaintenanceRequestStatusR\x06status:\xba\x01\xaa\xa8\xfd\x97\x02\xb3\x01\n" +
	"\x1anvsentinel.dgxc.nvidia.com\x12\x12MaintenanceRequest\x1a\x12maintenancerequest\"\x13maintenancerequests*\x02mr2\n" +
	"nvsentinel:$\n" +
	"\x04Node\x10\x03*\x1a.spec.healthEvent.nodeName: \n" +
	"\tStartTime\x10\x03\x18\x06*\x0f.spec.startTime@\x01B5Z3github.com/nvidia/nvsentinel/data-models/pkg/protosb\x06proto3"

var (
	file_maintenance_request_proto_rawDescOnce sync.Once
	file_maintenance_request_proto_rawDescData []byte
)

func file_maintenance_request_proto_rawDescGZIP() []byte {
	file_maintenance_request_proto_rawDescOnce.Do(func() {
		file_maintenance_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_maintenance_request_proto_rawDesc), len(file_maintenance_request_proto_rawDesc)))
	})
	return file_maintenance_request_proto_rawDescData
}

var file_maintenance_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_maintenance_request_proto_goTypes = []any{
	(*MaintenanceRequestSpec)(nil),   // 0: datamodels.MaintenanceRequestSpec
	(*MaintenanceRequestStatus)(nil), // 1: datamodels.MaintenanceRequestStatus
	(*MaintenanceRequest)(nil),       // 2: datamodels.MaintenanceRequest
	(*HealthEvent)(nil),              // 3: datamodels.HealthEvent
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
	(*Condition)(nil),                // 5: datamodels.Condition
}
var file_maintenance_request_proto_depIdxs = []int32{
	3, // 0: datamodels.MaintenanceRequestSpec.healthEvent:type_name -> datamodels.HealthEvent
	4, // 1: datamodels.MaintenanceRequestSpec.startTime:type_name -> google.protobuf.Timestamp
	5, // 2: datamodels.MaintenanceRequestStatus.conditions:type_name -> datamodels.Condition
	0, // 3: datamodels.MaintenanceRequest.spec:type_name -> datamodels.MaintenanceRequestSpec
	1, // 4: datamodels.MaintenanceRequest.status:type_name -> datamodels.MaintenanceRequestStatus
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_maintenance_request_proto_init() }
func file_maintenance_request_proto_init() {
	if File_maintenance_request_proto != nil {
		return
	}
	file_health_event_proto_init()
	file_external_remediation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_maintenance_request_proto_rawDesc), len(file_maintenance_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_maintenance_request_proto_goTypes,
		DependencyIndexes: file_maintenance_request_proto_depIdxs,
		MessageInfos:      file_maintenance_request_proto_msgTypes,
	}.Build()
	File_maintenance_request_proto = out.File
	file_maintenance_request_proto_goTypes = nil
	file_maintenance_request_proto_depIdxs = nil
}
